### ISSUE TITLE
Anyway to sort entities and add a cost column?

### ISSUE THREAD

**Issue by birth23** [thybag/ha-energy-entity-card#4]
I am trying to sort all entities and add a cost column.    Is there any way to achieve this with this card?
Looking to add functionality from custom:auto-entities and custom:template-entity-row or custom:multiple-entity-row and make energy-date-selection work?
![image](https://github.com/user-attachments/assets/37db53da-ece0-4863-85b8-5abedb4eb125)

```
type: custom:auto-entities
card:
  type: entities
filter:
  exclude:
    - entity_id: sensor.*cost
  include:
    - entity_id: sensor.*_today*
      options:
        type: custom:template-entity-row
        name: >-
          {{ state_attr(config.entity, 'friendly_name').split('Energy
          Today',1)[0] }}
        state: >-
          {{ ((states('sensor.Rate') | float(0) *
          states('this.entity_id') | float(0)) | round(2)) }} $  || {{
          states('this.entity_id') | round(2) }} kWh
sort:
  method: state
  reverse: true
  numeric: true
```
I tried the below but it doesn't re-sort when changing dates in the energy date selector and I couldn't figure out how to add a cost column
```
type: custom:auto-entities
card:
  type: entities
  title: Energy Devices
filter:
  exclude:
    - entity_id: sensor.*cost
  include:
    - entity_id: sensor.*_today*
      options:
        type: custom:energy-entity-row
sort:
  method: state
  reverse: true
  numeric: true
```
